"""cache off product fields

Revision ID: 3096d25a874d
Revises: bfdb9310bb3e
Create Date: 2025-12-24 00:47:01.121194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3096d25a874d'
down_revision: Union[str, Sequence[str], None] = 'bfdb9310bb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ingredients_text', sa.String(), nullable=True))
    op.add_column('products', sa.Column('allergens', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('traces', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('additives', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('analysis', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('diet_flags', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('nutriscore_grade', sa.String(length=8), nullable=True))
    op.add_column('products', sa.Column('ecoscore_grade', sa.String(length=8), nullable=True))
    op.add_column('products', sa.Column('ecoscore_score', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('off_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'off_last_synced_at')
    op.drop_column('products', 'ecoscore_score')
    op.drop_column('products', 'ecoscore_grade')
    op.drop_column('products', 'nutriscore_grade')
    op.drop_column('products', 'diet_flags')
    op.drop_column('products', 'analysis')
    op.drop_column('products', 'additives')
    op.drop_column('products', 'traces')
    op.drop_column('products', 'allergens')
    op.drop_column('products', 'ingredients_text')
    # ### end Alembic commands ###
